env:
  browser: false
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  {
    'no-console': 'off',
    'import/extensions': 'off',
    'no-restricted-syntax': ['error', 'ForOfStatement', 'LabeledStatement', 'WithStatement'],
  }
